import { lstat, realpath } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { findRepositoryRoot } from '@openge/forge-repository-files';
import type { CollectSourceInventoryOptions, SourceInventory, SourceInventoryEntry, SourceInventoryIssue, SourceInventoryRepository } from './contracts.js';
import { runGit } from './git.js';
const normalize = (value: string): string => value.replaceAll('\\', '/').replace(/^\.\//u, '').replace(/\/$/u, '');
const projectPath = (prefix: string, relative: string): string => [normalize(prefix), normalize(relative)].filter(Boolean).join('/');
const nullList = (value: string): readonly string[] => value.split('\0').filter(Boolean).map(normalize);
const stageMap = (value: string): ReadonlyMap<string, { readonly mode: string; readonly objectId: string }> => {
  const result = new Map<string, { mode: string; objectId: string }>();
  for (const record of value.split('\0').filter(Boolean)) { const tab = record.indexOf('\t'); if (tab < 0) continue; const parts = record.slice(0, tab).split(' '); const mode = parts[0]; const objectId = parts[1]; if (mode !== undefined && objectId !== undefined) result.set(normalize(record.slice(tab + 1)), { mode, objectId }); }
  return result;
};
const statusMap = (value: string): ReadonlyMap<string, string> => { const result = new Map<string,string>(); const records=value.split('\0').filter(Boolean); for(let index=0;index<records.length;index+=1){const record=records[index]; if(record===undefined) continue; const code=record.slice(0,2); result.set(normalize(record.slice(3)),code); if(code.includes('R')||code.includes('C')) index+=1;} return result; };
const describe = async (absolutePath: string): Promise<Pick<SourceInventoryEntry,'exists'|'size'|'type'>> => { try { const stat=await lstat(absolutePath); if(stat.isSymbolicLink()) return {exists:true,size:stat.size,type:'link'}; if(stat.isFile()) return {exists:true,size:stat.size,type:'file'}; if(stat.isDirectory()) return {exists:true,size:0,type:'directory'}; return {exists:true,size:stat.size,type:'other'}; } catch(error){ if((error as NodeJS.ErrnoException).code==='ENOENT') return {exists:false,size:0,type:'missing'}; throw error; } };
const isRepository = async (root: string, signal?: AbortSignal): Promise<boolean> => { const output=await runGit(root,['rev-parse','--show-toplevel'],{allowExitCodes:new Set([128]),...(signal===undefined?{}:{signal})}); return output.trim().length>0 && resolve(output.trim())===resolve(root); };
const submodulePaths = async (root: string, signal?: AbortSignal): Promise<readonly string[]> => { const output=await runGit(root,['config','-f','.gitmodules','--get-regexp',/^submodule\..*\.path$/u.source],{allowExitCodes:new Set([1]),...(signal===undefined?{}:{signal})}); return output.split(/\r?\n/u).filter(Boolean).map(line=>normalize(line.replace(/^\S+\s+/u,''))).sort(); };
const repositoryState = async (root:string,path:string,parentGitlink:string|null,signal?:AbortSignal):Promise<SourceInventoryRepository> => { const [head,branch,status]=await Promise.all([runGit(root,['rev-parse','HEAD'],signal===undefined?{}:{signal}),runGit(root,['branch','--show-current'],signal===undefined?{}:{signal}),runGit(root,['status','--porcelain=v1','-z','--untracked-files=all'],signal===undefined?{}:{signal})]); return Object.freeze({path,root,realRoot:await realpath(root),initialized:true,head:head.trim(),branch:branch.trim()||null,parentGitlink,dirty:status.length>0,statusCount:status.split('\0').filter(Boolean).length}); };
const entriesFor = async (root:string,prefix:string,signal?:AbortSignal):Promise<readonly SourceInventoryEntry[]> => { const [tracked,untracked,stage,status]=await Promise.all([runGit(root,['ls-files','--cached','-z'],signal===undefined?{}:{signal}),runGit(root,['ls-files','--others','--exclude-standard','-z'],signal===undefined?{}:{signal}),runGit(root,['ls-files','--stage','-z'],signal===undefined?{}:{signal}),runGit(root,['status','--porcelain=v1','-z','--untracked-files=all'],signal===undefined?{}:{signal})]); const trackedSet=new Set(nullList(tracked)); const untrackedSet=new Set(nullList(untracked)); const stages=stageMap(stage); const statuses=statusMap(status); const result:SourceInventoryEntry[]=[]; for(const relativePath of [...new Set([...trackedSet,...untrackedSet])].sort()){ if(stages.get(relativePath)?.mode==='160000') continue; const absolutePath=join(root,...relativePath.split('/')); result.push(Object.freeze({repositoryPath:prefix,relativePath,projectPath:projectPath(prefix,relativePath),absolutePath,tracked:trackedSet.has(relativePath),untracked:untrackedSet.has(relativePath),mode:stages.get(relativePath)?.mode??null,status:statuses.get(relativePath)??null,...await describe(absolutePath)})); } return result; };
export const collectSourceInventory = async (options: CollectSourceInventoryOptions): Promise<SourceInventory> => { const root=resolve(await findRepositoryRoot(options.sourceRoot,{...(options.signal===undefined?{}:{signal:options.signal})})); const repositories:SourceInventoryRepository[]=[]; const entries:SourceInventoryEntry[]=[]; const issues:SourceInventoryIssue[]=[]; const queue:Array<{root:string;path:string;parentGitlink:string|null}>=[{root,path:'',parentGitlink:null}]; const seen=new Set<string>(); while(queue.length>0){const current=queue.shift(); if(current===undefined||seen.has(current.path)) continue; seen.add(current.path); if(!(await isRepository(current.root,options.signal))){repositories.push(Object.freeze({path:current.path,root:current.root,realRoot:null,initialized:false,head:null,branch:null,parentGitlink:current.parentGitlink,dirty:null,statusCount:null})); issues.push(Object.freeze({code:'SUBMODULE_UNINITIALIZED',path:current.path,blocking:true})); continue;} const state=await repositoryState(current.root,current.path,current.parentGitlink,options.signal); repositories.push(state); entries.push(...await entriesFor(current.root,current.path,options.signal)); const stages=stageMap(await runGit(current.root,['ls-files','--stage','-z'],options.signal===undefined?{}:{signal:options.signal})); for(const relative of await submodulePaths(current.root,options.signal)){const gitlink=stages.get(relative); const path=projectPath(current.path,relative); if(gitlink?.mode!=='160000'){issues.push(Object.freeze({code:'SUBMODULE_GITLINK_MISSING',path,blocking:true})); continue;} queue.push({root:join(current.root,...relative.split('/')),path,parentGitlink:gitlink.objectId});}}
  for(const repository of repositories){if(repository.initialized&&repository.parentGitlink!==null&&repository.head!==repository.parentGitlink&&options.submoduleHeadPolicy!=='allow-checked-out') issues.push(Object.freeze({code:'SUBMODULE_HEAD_MISMATCH',path:repository.path,expected:repository.parentGitlink,...(repository.head===null?{}:{actual:repository.head}),blocking:true}));}
  repositories.sort((a,b)=>a.path.localeCompare(b.path,'en')); entries.sort((a,b)=>a.projectPath.localeCompare(b.projectPath,'en')); issues.sort((a,b)=>a.path.localeCompare(b.path,'en'));
  return Object.freeze({version:1,sourceRoot:root,repositories:Object.freeze(repositories),entries:Object.freeze(entries),issues:Object.freeze(issues),summary:Object.freeze({repositoryCount:repositories.length,initializedRepositoryCount:repositories.filter(value=>value.initialized).length,candidateCount:entries.length,trackedCount:entries.filter(value=>value.tracked).length,untrackedCount:entries.filter(value=>value.untracked).length,dirtyRepositoryCount:repositories.filter(value=>value.dirty===true).length})});
};
