import { mkdir, readdir, realpath } from 'node:fs/promises';
import { basename, dirname, isAbsolute, relative, resolve } from 'node:path';
import { calculateBytesIntegrity } from '@openge/forge-artifact-integrity';
import { defineGeneratedArtifactPlan } from '@openge/forge-generated-artifacts';
import { inspectGeneratedArtifacts, publishGeneratedArtifacts } from '@openge/forge-generated-artifacts/node';
import type { SnapshotManifest, SnapshotManifestInput } from '../contracts.js';
import type { SourceSnapshotBundle } from '../content-contracts.js';
import { SourceSnapshotError } from '../errors.js';
import { compareSnapshotFiles } from '../changes.js';
import { createSnapshotManifest } from '../manifest.js';
import { createTextSnapshotManifest } from '../text-manifest.js';
import type { PublishSourceSnapshotOptions, SourceSnapshotPublicationResult, SourceSnapshotVerificationResult, VerifyPublishedSourceSnapshotOptions } from './contracts.js';
import { acquireSourceSnapshotLock } from './lock.js';
import { readManagedBytes, readManagedText } from './managed-read.js';
import { resolveStorageLayout, type ResolvedSourceSnapshotLayout } from './layout.js';

const SNAPSHOT_PATTERN = /^snapshot-[a-f0-9]{64}$/u;
const code=(value:unknown):string|undefined=>value instanceof Error&&'code'in value&&typeof value.code==='string'?value.code:undefined;
const isInside=(parent:string,candidate:string):boolean=>{const value=relative(parent,candidate);return value===''||(!value.startsWith('..')&&!isAbsolute(value));};
const canonicalPotential = async (input:string):Promise<string> => {
  let current=resolve(input); const missing:string[]=[];
  while(true){try{return resolve(await realpath(current),...missing);}catch(error){if(code(error)!=='ENOENT')throw error; const parent=dirname(current); if(parent===current)throw error; missing.unshift(basename(current)); current=parent;}}
};
export const assertSourceTargetSeparation = async (sourceRoot:string,targetRoot:string):Promise<void> => {
  const [source,target]=await Promise.all([canonicalPotential(sourceRoot),canonicalPotential(targetRoot)]);
  if(isInside(source,target)||isInside(target,source))throw new SourceSnapshotError('SOURCE_TARGET_OVERLAP',{sourceRoot,targetRoot});
};
const parseJson = (text:string, errorCode:'TARGET_NOT_OWNED'|'SNAPSHOT_ID_MISMATCH'):unknown => {try{return JSON.parse(text);}catch{throw new SourceSnapshotError(errorCode);}};
const ensureOwner = async (targetRoot:string,ownerId:string,projectId:string,layout:ResolvedSourceSnapshotLayout):Promise<void> => {
  if(ownerId.length===0)throw new SourceSnapshotError('INVALID_INPUT',{field:'ownerId'}); await mkdir(targetRoot,{recursive:true});
  const existing=await readManagedText(targetRoot,layout.ownerFile,false);
  if(existing!==undefined){const parsed=parseJson(existing,'TARGET_NOT_OWNED'); if(typeof parsed!=='object'||parsed===null)throw new SourceSnapshotError('TARGET_NOT_OWNED'); const value=parsed as {ownerId?:unknown;projectId?:unknown}; if(value.ownerId!==ownerId)throw new SourceSnapshotError('TARGET_OWNER_MISMATCH'); if(value.projectId!==projectId)throw new SourceSnapshotError('TARGET_PROJECT_MISMATCH'); return;}
  const allowed=new Set(layout.protectedTopLevelDirectories); const unknown=(await readdir(targetRoot,{withFileTypes:true})).filter(entry=>!(entry.isDirectory()&&allowed.has(entry.name))).map(entry=>entry.name);
  if(unknown.length>0)throw new SourceSnapshotError('TARGET_NOT_OWNED',{entries:unknown});
  await writeMutableSourceArtifacts(targetRoot,[{path:layout.ownerFile,content:`${JSON.stringify({schemaVersion:1,ownerId,projectId},null,2)}\n`}],layout);
};
export const readSourceSnapshotOwner = async (targetRoot:string,ownerId:string,layout:ResolvedSourceSnapshotLayout):Promise<{projectId:string}> => {
  const text=await readManagedText(targetRoot,layout.ownerFile,false); if(text===undefined)throw new SourceSnapshotError('TARGET_NOT_OWNED'); const parsed=parseJson(text,'TARGET_NOT_OWNED'); if(typeof parsed!=='object'||parsed===null)throw new SourceSnapshotError('TARGET_NOT_OWNED'); const value=parsed as {ownerId?:unknown;projectId?:unknown}; if(value.ownerId!==ownerId)throw new SourceSnapshotError('TARGET_OWNER_MISMATCH'); if(typeof value.projectId!=='string')throw new SourceSnapshotError('TARGET_NOT_OWNED'); return {projectId:value.projectId};
};
const assertSnapshotId=(value:string):void=>{if(!SNAPSHOT_PATTERN.test(value))throw new SourceSnapshotError('INVALID_SNAPSHOT_ID',{snapshotId:value});};
const parseEntry=(text:string):string=>{const value=text.match(/^snapshot_id:\s*(\S+)\s*$/mu)?.[1]; if(value===undefined)throw new SourceSnapshotError('INVALID_SNAPSHOT_ID'); assertSnapshotId(value); return value;};
export const readCurrentSourceSnapshotId=async(targetRoot:string,layout:ResolvedSourceSnapshotLayout,required:boolean):Promise<string|null>=>{const text=await readManagedText(targetRoot,layout.entryFile,false); if(text===undefined){if(required)throw new SourceSnapshotError('ENTRY_MISSING');return null;}return parseEntry(text);};
const snapshotPath=(snapshotId:string,name:string):string=>`snapshots/${snapshotId}/${name}`;
export const loadStoredSourceSnapshotManifest = async (targetRoot:string,snapshotId:string):Promise<SnapshotManifest> => {
  assertSnapshotId(snapshotId); const text=await readManagedText(targetRoot,snapshotPath(snapshotId,'SNAPSHOT.json'),false); if(text===undefined)throw new SourceSnapshotError('SNAPSHOT_MISSING',{snapshotId}); const parsed=parseJson(text,'SNAPSHOT_ID_MISMATCH'); if(typeof parsed!=='object'||parsed===null)throw new SourceSnapshotError('SNAPSHOT_ID_MISMATCH',{snapshotId}); const value=parsed as Partial<SnapshotManifest>;
  try {const recreated=await createSnapshotManifest({projectId:value.projectId as string,policyVersion:value.policyVersion as string,publishedAt:value.publishedAt as number,repositories:value.repositories as SnapshotManifestInput['repositories'],files:value.files as SnapshotManifestInput['files'],objects:value.objects as SnapshotManifestInput['objects']}); if(value.snapshotId!==snapshotId||recreated.snapshotId!==snapshotId)throw new SourceSnapshotError('SNAPSHOT_ID_MISMATCH',{snapshotId}); return recreated;} catch(error){if(error instanceof SourceSnapshotError&&error.code==='SNAPSHOT_ID_MISMATCH')throw error; throw new SourceSnapshotError('SNAPSHOT_ID_MISMATCH',{snapshotId});}
};
const verifyObject = async(targetRoot:string,object:SnapshotManifest['objects'][number]):Promise<void>=>{const bytes=await readManagedBytes(targetRoot,object.path,false); if(bytes===undefined)throw new SourceSnapshotError('OBJECT_MISSING',{path:object.path}); const integrity=await calculateBytesIntegrity(bytes); if(integrity.sha256!==object.sha256||integrity.byteLength!==object.byteLength)throw new SourceSnapshotError('OBJECT_INTEGRITY_MISMATCH',{path:object.path});};
const renderEntry=(manifest:SnapshotManifest):string=>['schema_version: 1',`snapshot_id: ${manifest.snapshotId}`,'local_status: LOCAL_VERIFIED',`project_id: ${manifest.projectId}`,`published_at_ms: ${manifest.publishedAt}`,'','# Source Snapshot','',`Current snapshot: \`${manifest.snapshotId}\`.`, '',`Manifest: \`snapshots/${manifest.snapshotId}/SNAPSHOT.json\`.`,`Index: \`snapshots/${manifest.snapshotId}/INDEX.md\`.`, ''].join('\n');
const renderIndex=(manifest:SnapshotManifest):string=>{const lines=['# Source Snapshot','',`- Snapshot ID: \`${manifest.snapshotId}\``,`- Project ID: \`${manifest.projectId}\``,`- Source files: ${manifest.files.length}`,`- Objects: ${manifest.objects.length}`,'','## Objects','']; for(const object of manifest.objects)lines.push(`- \`${object.path}\``); lines.push('','## Files',''); for(const file of manifest.files)lines.push(`- \`${file.path}\``); lines.push(''); return lines.join('\n');};
const renderChanges=(previous:SnapshotManifest|null,current:SnapshotManifest):string=>{const changes=compareSnapshotFiles(previous,current); return `${JSON.stringify({previousSnapshotId:previous?.snapshotId??null,currentSnapshotId:current.snapshotId,...changes},null,2)}\n`;};
const generatedOptions=(layout:ResolvedSourceSnapshotLayout)=>({pathCaseSensitivity:layout.pathCaseSensitivity});
export const writeMutableSourceArtifacts = async(targetRoot:string,artifacts:readonly {path:string;content:string}[],layout:ResolvedSourceSnapshotLayout):Promise<void>=>{const plan=defineGeneratedArtifactPlan({artifacts,retiredPaths:[]}); const result=await publishGeneratedArtifacts(targetRoot,plan,generatedOptions(layout)); if(result.diagnostics.length>0)throw new SourceSnapshotError('PUBLICATION_FAILED',{diagnostics:result.diagnostics});};
const writeImmutable = async(targetRoot:string,artifacts:readonly {path:string;content:string}[],layout:ResolvedSourceSnapshotLayout,collisionCode:'OBJECT_IMMUTABLE_MISMATCH'|'SNAPSHOT_COLLISION'):Promise<{written:number;unchanged:number}>=>{const plan=defineGeneratedArtifactPlan({artifacts,retiredPaths:[]}); const inspected=await inspectGeneratedArtifacts(targetRoot,plan,generatedOptions(layout)); if(inspected.stale.length>0)throw new SourceSnapshotError(collisionCode,{paths:inspected.stale}); const result=await publishGeneratedArtifacts(targetRoot,plan,generatedOptions(layout)); if(result.diagnostics.length>0)throw new SourceSnapshotError('PUBLICATION_FAILED',{diagnostics:result.diagnostics}); return {written:result.written.length,unchanged:result.unchanged.length};};
const validateBundle=async(bundle:SourceSnapshotBundle):Promise<void>=>{const recreated=await createTextSnapshotManifest({projectId:bundle.manifest.projectId,policyVersion:bundle.manifest.policyVersion,publishedAt:bundle.manifest.publishedAt,repositories:bundle.manifest.repositories,textPackage:bundle.textPackage}); if(recreated.snapshotId!==bundle.manifest.snapshotId)throw new SourceSnapshotError('BUNDLE_MISMATCH');};
export const verifyPublishedSourceSnapshot = async(options:VerifyPublishedSourceSnapshotOptions):Promise<SourceSnapshotVerificationResult> => {
  const layout=resolveStorageLayout(options); const owner=await readSourceSnapshotOwner(options.targetRoot,options.ownerId,layout); const requested=options.snapshotId; const snapshotId=requested??await readCurrentSourceSnapshotId(options.targetRoot,layout,true) as string; assertSnapshotId(snapshotId); const entryBefore=requested===undefined?snapshotId:null; const manifest=await loadStoredSourceSnapshotManifest(options.targetRoot,snapshotId); if(owner.projectId!==manifest.projectId)throw new SourceSnapshotError('TARGET_PROJECT_MISMATCH'); await Promise.all(manifest.objects.map(object=>verifyObject(options.targetRoot,object))); if(requested===undefined){const entryAfter=await readCurrentSourceSnapshotId(options.targetRoot,layout,true); if(entryAfter!==entryBefore)throw new SourceSnapshotError('ENTRY_MISSING',{reason:'entry-changed'});} return Object.freeze({status:'LOCAL_VERIFIED',snapshotId,objectCount:manifest.objects.length,sourceFileCount:manifest.files.length});
};
export const publishSourceSnapshot = async(bundle:SourceSnapshotBundle,options:PublishSourceSnapshotOptions):Promise<SourceSnapshotPublicationResult> => {
  await assertSourceTargetSeparation(options.sourceRoot,options.targetRoot); await validateBundle(bundle); const layout=resolveStorageLayout(options); const release=await acquireSourceSnapshotLock(options.lockPath); try{await ensureOwner(options.targetRoot,options.ownerId,bundle.manifest.projectId,layout); const current=await readCurrentSourceSnapshotId(options.targetRoot,layout,false); let previous:SnapshotManifest|null=null; if(current!==null){await verifyPublishedSourceSnapshot({...options,snapshotId:current}); previous=await loadStoredSourceSnapshotManifest(options.targetRoot,current); if(current===bundle.manifest.snapshotId)return Object.freeze({status:'NO_CHANGES',snapshotId:current,objectCount:bundle.manifest.objects.length,sourceFileCount:bundle.manifest.files.length,writtenObjects:0,reusedObjects:bundle.manifest.objects.length});}
    const objectResult=await writeImmutable(options.targetRoot,bundle.textPackage.objects.map(object=>({path:object.path,content:object.content})),layout,'OBJECT_IMMUTABLE_MISMATCH'); const id=bundle.manifest.snapshotId; const snapshotArtifacts=[{path:snapshotPath(id,'SNAPSHOT.json'),content:`${JSON.stringify(bundle.manifest,null,2)}\n`},{path:snapshotPath(id,'INDEX.md'),content:renderIndex(bundle.manifest)},{path:snapshotPath(id,'CHANGES.json'),content:renderChanges(previous,bundle.manifest)}]; await writeImmutable(options.targetRoot,snapshotArtifacts,layout,'SNAPSHOT_COLLISION'); await verifyPublishedSourceSnapshot({...options,snapshotId:id}); await writeMutableSourceArtifacts(options.targetRoot,[{path:layout.entryFile,content:renderEntry(bundle.manifest)}],layout); const verification=await verifyPublishedSourceSnapshot({...options}); return Object.freeze({...verification,status:'LOCAL_VERIFIED',writtenObjects:objectResult.written,reusedObjects:objectResult.unchanged});
  }finally{await release();}
};
